In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from electronfactors import (
    new_reading, calc_and_display, energy_to_reference_depth, 
    initialise)

In [2]:
data = dict()

## 18 MeV

In [3]:
energy_to_reference_depth(18)

array([30])

In [4]:
# Standard insert 10app 18MeV 100MU
np.mean([1.095, 1.096])

1.0954999999999999

In [5]:
key = 'P13'

data = initialise(
    key=key, data=data,
    reference=1.096,
    energy=18
)

data = new_reading(
    key=key, data=data,
    ionisation=np.array([1.092, 1.093]),
    depth=30
)

data[key]['factor'] = calc_and_display(**data[key])

Cutout factor = 0.997 | -0.3%
Inverse factor = 1.003 | 0.3%


In [6]:
# Standard insert 10app 18MeV 100MU
np.mean([1.096, 1.097])

1.0965

## 15 MeV

In [7]:
energy_to_reference_depth(15)

array([27])

In [8]:
# Standard insert 10app 15MeV 100MU
np.mean([1.076, 1.078])

1.077

In [9]:
# Standard insert 10app 15MeV 100MU
np.mean([1.076, 1.078])

1.077

In [10]:
key = '6.7x12cm_15MeV'

data = initialise(
    key=key, data=data,
    reference=1.077,
    energy=15
)

data = new_reading(
    key=key, data=data,
    ionisation=np.array([1.075, 1.076]),
    depth=27
)

data[key]['factor'] = calc_and_display(**data[key])

Cutout factor = 0.999 | -0.1%
Inverse factor = 1.001 | 0.1%


In [11]:
# Standard insert 10app 15MeV 100MU
np.mean([1.076, 1.078])

1.077

In [12]:
key = '6.7x12cm_15MeV_old'

data = initialise(
    key=key, data=data,
    reference=1.077,
    energy=15
)

data = new_reading(
    key=key, data=data,
    ionisation=np.array([1.088, 1.089]),
    depth=27
)

data[key]['factor'] = calc_and_display(**data[key])

Cutout factor = 1.011 | 1.1%
Inverse factor = 0.989 | -1.1%


In [13]:
# Standard insert 10app 15MeV 100MU
np.mean([1.077, 1.077])

1.077

## 6 MeV

In [14]:
energy_to_reference_depth(6)

array([13])

In [15]:
# Standard insert 10app 6MeV 100MU
np.mean([1.016, 1.016])

1.016

In [16]:
key = '6.7x12cm_6MeV'

data = initialise(
    key=key, data=data,
    reference=1.016,
    energy=6
)

data = new_reading(
    key=key, data=data,
    ionisation=np.array([1.014, 1.014]),
    depth=13
)

data[key]['factor'] = calc_and_display(**data[key])

Cutout factor = 0.998 | -0.2%
Inverse factor = 1.002 | 0.2%


In [17]:
# Standard insert 10app 6MeV 100MU
np.mean([1.016, 1.015])

1.0154999999999998

## 9 MeV

In [18]:
energy_to_reference_depth(9)

array([20])

In [19]:
# Standard insert 10app 9MeV 100MU
np.mean([1.033, 1.033])

1.0329999999999999

In [20]:
key = '6.7x12cm_9MeV'

data = initialise(
    key=key, data=data,
    reference=1.033,
    energy=9
)

data = new_reading(
    key=key, data=data,
    ionisation=np.array([1.032, 1.033]),
    depth=20
)

data[key]['factor'] = calc_and_display(**data[key])

Cutout factor = 1.000 | -0.0%
Inverse factor = 1.000 | 0.0%


In [21]:
# Standard insert 10app 9MeV 100MU
np.mean([1.033, 1.033])

1.0329999999999999

## 18 MeV

In [22]:
energy_to_reference_depth(18)

array([30])

In [23]:
# Standard insert 10app 18MeV 100MU
np.mean([1.095, 1.097])

1.0960000000000001

In [24]:
key = '6.7x12cm_18MeV'

data = initialise(
    key=key, data=data,
    reference=1.096,
    energy=18
)

data = new_reading(
    key=key, data=data,
    ionisation=np.array([1.094, 1.096]),
    depth=30
)

data[key]['factor'] = calc_and_display(**data[key])

Cutout factor = 0.999 | -0.1%
Inverse factor = 1.001 | 0.1%


In [25]:
# Standard insert 10app 18MeV 100MU
np.mean([1.096, 1.097])

1.0965