In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import sys
sys.path.append("../")

from electronfactors.measurement.utilities import *

In [2]:
data = dict()

## 12 MeV

In [3]:
energy_to_reference_depth(12)

array([25])

In [4]:
# Standard insert 10app 12MeV
np.mean([1.031, 1.031])

1.0309999999999999

In [5]:
key = 'P3_12MeV'

data = initialise(
    key=key, data=data,
    reference=1.031,
    energy=12    
)

data = new_reading(
    key=key, data=data,
    ionisation=[1.030, 1.031, 1.030],
    depth=25    
)

data[key]['factor'] = calc_and_display(**data[key])

Cutout factor = 0.999 | -0.1%
Inverse factor = 1.001 | 0.1%


In [6]:
# Standard insert 10app 12MeV
np.mean([1.031])

1.0309999999999999

## 6 MeV

In [7]:
energy_to_reference_depth(6)

array([13])

In [8]:
# Standard insert 10app 6MeV
np.mean([0.9976, 0.9996, 0.999])

0.99873333333333336

In [9]:
key = 'P3_6MeV'

data = initialise(
    key=key, data=data,
    reference=0.999,
    energy=6    
)

data = new_reading(
    key=key, data=data,
    ionisation=[1.001, 1.003, 1.001],
    depth=13    
)

data[key]['factor'] = calc_and_display(**data[key])

Cutout factor = 1.003 | 0.3%
Inverse factor = 0.997 | -0.3%


In [10]:
# Standard insert 10app 6MeV
np.mean([0.9986])

0.99860000000000004

## 9 MeV

In [11]:
energy_to_reference_depth(9)

array([20])

In [12]:
# Standard insert 10app 9MeV
np.mean([1.011, 1.012, 1.012])

1.0116666666666665

In [13]:
key = 'P3_9MeV'

data = initialise(
    key=key, data=data,
    reference=1.0115,
    energy=9  
)

data = new_reading(
    key=key, data=data,
    ionisation=[1.013, 1.013],
    depth=20    
)

data[key]['factor'] = calc_and_display(**data[key])

Cutout factor = 1.001 | 0.1%
Inverse factor = 0.999 | -0.1%


In [14]:
# Standard insert 10app 9MeV
np.mean([1.011, 1.012])

1.0114999999999998

## 15 MeV

In [15]:
energy_to_reference_depth(15)

array([30])

In [16]:
# Standard insert 10app 15MeV
np.mean([1.046, 1.046])

1.046

In [17]:
key = 'P3_15MeV'

data = initialise(
    key=key, data=data,
    reference=1.046,
    energy=15  
)

data = new_reading(
    key=key, data=data,
    ionisation=[1.043, 1.044, 1.043],
    depth=30    
)

data[key]['factor'] = calc_and_display(**data[key])

Cutout factor = 0.997 | -0.3%
Inverse factor = 1.003 | 0.3%


In [18]:
# Standard insert 10app 15MeV
np.mean([1.046])

1.046

## 18 MeV

In [19]:
energy_to_reference_depth(18)

array([30])

In [20]:
key = 'P3_18MeV'

data = initialise(
    key=key, data=data,
    reference=1.0755,
    energy=15  
)

data = new_reading(
    key=key, data=data,
    ionisation=[1.073, 1.075, 1.076, 1.077, 1.075],
    depth=30    
)

data[key]['factor'] = calc_and_display(**data[key])

Cutout factor = 1.000 | -0.0%
Inverse factor = 1.000 | 0.0%


In [21]:
# Standard insert 10app 18MeV
np.mean([1.075, 1.076])

1.0754999999999999